---
version: '3'

services:

  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec ruby rights_api.rb -o 0.0.0.0
    environment:
#      SOLR_URL: http://solr-sdr-catalog:9033/solr/catalog
      RIGHTS_DATABASE_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
    depends_on:
#      - solr-sdr-catalog
      - mariadb

  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bash -c "/usr/local/bin/wait-for mariadb:3306 && bundle exec rspec"
    environment:
#      SOLR_URL: http://solr-sdr-catalog:9033/solr/catalog
      RIGHTS_DATABASE_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
    depends_on:
#      - solr-sdr-catalog
      - mariadb

#  solr-sdr-catalog:
#    image: ghcr.io/hathitrust/catalog-solr-sample
#    ports:
#      - "9033:9033"

  mariadb:
    image: ghcr.io/hathitrust/db-image
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights

volumes:
  gem_cache:
