---
version: '3'

services:

  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    environment:
      RIGHTS_DATABASE_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
    depends_on:
      - mariadb

  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bash -c "/usr/local/bin/wait-for mariadb:3306 && bundle exec rspec"
    environment:
      RIGHTS_DATABASE_CONNECTION_STRING: "mysql2://ht_rights:ht_rights@mariadb/ht"
      RIGHTS_API_NO_LOG: 1
    depends_on:
      - mariadb

  mariadb:
    image: ghcr.io/hathitrust/db-image
    volumes:
      - ./sql/100_rights_log.sql:/docker-entrypoint-initdb.d/100_rights_log.sql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ht
      MYSQL_USER: ht_rights
      MYSQL_PASSWORD: ht_rights

volumes:
  gem_cache:
