name: Build latest from main and deploy to staging

on:
  workflow_run:
    workflows: ['Run Tests']
    branches: ['main']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/${{ github.repository }}-unstable
          dockerfile: Dockerfile.prod
          tag: ${{ github.sha }}
          push_latest: true
          registry_token: ${{ github.token }}

# TODO: automate deployment w/ argocd
# for now - update image in
# https://github.com/hathitrust/ht_tanka/blob/main/environments/rights_api/staging/main.jsonnet
