name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to package registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}


      - name: Set up tests
        run: |
          docker compose build
          docker compose run web bundle install

      - name: Run standardrb
        run: docker compose run web bundle exec standardrb

      - name: Run tests
        run: docker compose run web bundle exec rspec

      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
